### ISSUE TITLE
It is not possible build Docker image

### ISSUE THREAD

**Issue by tmszi** [gisquick/gisquick-server-next#2]
**Describe the bug**
It is not possible build Docker image.

**To Reproduce**

1. `cd /tmp && git clone https://github.com/gisquick/gisquick-server-next.git && cd gisquick-server-next`
2. Build Docker image `docker build -t gisquick/server -f ./docker/Dockerfile-alpine .`

```
Step 12/27 : COPY . .
 ---> c991e244cb62
Step 13/27 : RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /go/bin/gisquick cmd/main.go
 ---> Running in 5f3c76874fab
internal/infrastructure/email/accounts.go:11:2: no required module provides package github.com/gisquick/gisquick-server/internal/infrastructure/maps; to add it:
	go get github.com/gisquick/gisquick-server/internal/infrastructure/maps
The command '/bin/sh -c CGO_ENABLED=0 go build -ldflags="-s -w" -o /go/bin/gisquick cmd/main.go' returned a non-zero code: 1
```

Module path doesn't exists:

https://github.com/gisquick/gisquick-server-next/blob/8f087809ae21826ddd188bf470c54e08a342d17e/internal/infrastructure/email/accounts.go#L11

**Expected behavior**
A Docker image should be built.

**Comment by marcel-dancak** [comment]
It is fixed now, I just wrote wrong issue number in the commit message. Who should though that first issue will have number 2...
